manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kzyz
      url-base: https://github.com/kzyz
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk_az1uball_driver
      remote: kzyz
      revision: main
  self:
    path: config
